name: holistic_gaming_site
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^4.2.1
  chewie: ^1.5.0
  cloud_firestore: ^4.7.1
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  equatable: ^2.0.5
  firebase_analytics: ^10.4.1
  firebase_analytics_web: ^0.5.4+1
  firebase_core: ^2.13.0
  firebase_storage: ^11.2.1
  fl_chart: ^0.62.0
  go_router: ^7.0.1
  http: ^0.13.0
  lottie: ^2.3.2
  pdfx: ^2.3.0
  url_launcher: ^6.1.11
  video_player: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo/hg-logo.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/images/logo/hg-logo.png"
    background_color: "#fdfdfd"
    theme_color: "#fdfdfd"
  windows:
    generate: true
    image_path: "assets/images/logo/hg-logo.png"
    icon_size: 48 

flutter:
  uses-material-design: true

  assets:
    - assets/docs/
    - assets/images/
    - assets/images/connections/
    - assets/images/games/
    - assets/images/home/
    - assets/images/logo/
    - assets/images/research/
    - assets/images/splash/
    - assets/images/squad/david/
    - assets/images/squad/david/books/
    - assets/images/squad/david/edtech/
    - assets/images/pixatool/gifs/
    - assets/images/pixatool/pictures/
    - assets/images/pixatool/video-posters/
    - assets/images/thanks/

fonts: 
  - family: OpenSans
    fonts: 
      - asset: assets/fonts/OpenSans/OpenSans-Light.tff
        weight: 300
      - asset: assets/fonts/OpenSans/OpenSans-LightItalic.tff
        style: italic
        weight: 300
      - asset: assets/fonts/OpenSans/OpenSans-Regular.tff
        weight: 400
      - asset: assets/fonts/OpenSans/OpenSans-Italic.tff
        style: italic
        weight: 400
      - asset: assets/fonts/OpenSans/OpenSans-Medium.tff
        weight: 500
      - asset: assets/fonts/OpenSans/OpenSans-MediumItalic.tff
        style: italic
        weight: 500
      - asset: assets/fonts/OpenSans/OpenSans-SemiBold.tff
        weight: 600
      - asset: assets/fonts/OpenSans/OpenSans-SemiBoldItalic.tff
        style: italic
        weight: 600
      - asset: assets/fonts/OpenSans/OpenSans-Bold.tff
        weight: 700
      - asset: assets/fonts/OpenSans/OpenSans-BoldItalic.tff
        style: italic
        weight: 700
      - asset: assets/fonts/OpenSans/OpenSans-ExtraBold.tff
        weight: 800
      - asset: assets/fonts/OpenSans/OpenSans-ExtraBoldItalic.tff
        style: italic
        weight: 800
        
