name: holistic_gaming_site
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^5.0.0
  chewie: ^1.5.0
  cloud_firestore: ^4.7.1
  cupertino_icons: ^1.0.2
  email_validator: ^3.0.0
  equatable: ^2.0.5
  firebase_analytics: ^10.4.1
  firebase_analytics_web: ^0.5.4+1
  firebase_core: ^2.13.0
  firebase_storage: ^11.2.1
  fl_chart: ^0.69.0
  flutter_widget_from_html: ^0.16.0
  go_router: ^14.2.7
  http: ^1.2.2
  lottie: ^3.1.2
  pdfx: ^2.8.0
  url_launcher: ^6.1.11
  video_player: ^2.6.1
  # webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  image_path: "assets/images/logo/hg-logo.png"
  web:
    generate: true
    image_path: "assets/images/logo/hg-logo.png"
    background_color: "#fdfdfd"
    theme_color: "#fdfdfd"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/docs/
    - assets/html/
    - assets/images/
    - assets/images/connections/
    - assets/images/games/
    - assets/images/games/generic-logos/
    - assets/images/home/
    - assets/images/logo/
    - assets/images/research/
    - assets/images/splash/
    - assets/images/splash/
    - assets/images/squad/david/
    - assets/images/squad/david/books/
    - assets/images/squad/david/edtech/
    - assets/images/pixatool/gifs/
    - assets/images/pixatool/pictures/
    - assets/images/pixatool/video-posters/
    - assets/images/thanks/

fonts:
  - family: OpenSans
    fonts:
      - asset: assets/fonts/OpenSans/OpenSans-Light.tff
        weight: 300
      - asset: assets/fonts/OpenSans/OpenSans-LightItalic.tff
        style: italic
        weight: 300
      - asset: assets/fonts/OpenSans/OpenSans-Regular.tff
        weight: 400
      - asset: assets/fonts/OpenSans/OpenSans-Italic.tff
        style: italic
        weight: 400
      - asset: assets/fonts/OpenSans/OpenSans-Medium.tff
        weight: 500
      - asset: assets/fonts/OpenSans/OpenSans-MediumItalic.tff
        style: italic
        weight: 500
      - asset: assets/fonts/OpenSans/OpenSans-SemiBold.tff
        weight: 600
      - asset: assets/fonts/OpenSans/OpenSans-SemiBoldItalic.tff
        style: italic
        weight: 600
      - asset: assets/fonts/OpenSans/OpenSans-Bold.tff
        weight: 700
      - asset: assets/fonts/OpenSans/OpenSans-BoldItalic.tff
        style: italic
        weight: 700
      - asset: assets/fonts/OpenSans/OpenSans-ExtraBold.tff
        weight: 800
      - asset: assets/fonts/OpenSans/OpenSans-ExtraBoldItalic.tff
        style: italic
        weight: 800
  - family: NotoSans
    fonts:
      - asset: assets/fonts/NotoSans/NotoSansJP-Thin.tff
        weight: 200
      - asset: assets/fonts/NotoSans/NotoSansJP-Light.tff
        weight: 300
      - asset: assets/fonts/NotoSans/NotoSansJP-Regular.tff
        weight: 400
      - asset: assets/fonts/NotoSans/NotoSansJP-Medium.tff
        weight: 500
      - asset: assets/fonts/NotoSans/NotoSansJP-Bold.tff
        weight: 700
